<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::query()->where('email', 'user@landsite.test')->first();

        if (! $user) {
            return;
        }

        $properties = [
            [
                'title' => 'Prantik, 70/1',
                'purpose' => 'rent',
                'property_type' => 'Apartment',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 38000,
                'area_size' => 1450,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'garages' => 1,
                'location' => 'Dhanmondi 6A, Dhaka',
                'district' => 'Dhaka',
                'division' => 'Dhaka',
                'postal_code' => '1209',
                'address' => 'Flat F#D4, House#70/1, Dhanmondi 6A, Dhaka',
                'description' => 'Family-ready apartment near main road with good daylight and nearby daily essentials.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(7),
            ],
            [
                'title' => 'Bashundhara Lake View Apartment',
                'purpose' => 'sale',
                'property_type' => 'Apartment',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 12500000,
                'area_size' => 1825,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'garages' => 1,
                'location' => 'Bashundhara R/A, Dhaka',
                'district' => 'Dhaka',
                'division' => 'Dhaka',
                'postal_code' => '1229',
                'address' => 'Road 12, Block C, Bashundhara R/A, Dhaka',
                'description' => 'Spacious apartment with balcony view, lift access, and quiet residential surroundings.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8),
            ],
            [
                'title' => 'Uttara Sector 7 Modern Flat',
                'purpose' => 'rent',
                'property_type' => 'Apartment',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 52000,
                'area_size' => 1680,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'garages' => 1,
                'location' => 'Sector 7, Uttara, Dhaka',
                'district' => 'Dhaka',
                'division' => 'Dhaka',
                'postal_code' => '1230',
                'address' => 'Road 5, Sector 7, Uttara, Dhaka',
                'description' => 'Modern flat with lift, generator, and easy airport road access.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'title' => 'Mirpur DOHS Family Home',
                'purpose' => 'sale',
                'property_type' => 'House',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 28500000,
                'area_size' => 2400,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'garages' => 2,
                'location' => 'Mirpur DOHS, Dhaka',
                'district' => 'Dhaka',
                'division' => 'Dhaka',
                'postal_code' => '1216',
                'address' => 'Lane 3, Mirpur DOHS, Dhaka',
                'description' => 'Independent family house with parking and rooftop access.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDay(),
            ],
            [
                'title' => 'Purbachal Residential Plot 7 Katha',
                'purpose' => 'sale',
                'property_type' => 'Land',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 21000000,
                'area_size' => 5040,
                'bedrooms' => null,
                'bathrooms' => null,
                'garages' => 0,
                'location' => 'Sector 18, Purbachal',
                'district' => 'Narayanganj',
                'division' => 'Dhaka',
                'postal_code' => '1460',
                'address' => 'Sector 18, Purbachal New Town',
                'description' => 'Residential plot in developing block with road access and utility readiness nearby.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'title' => 'Sylhet Mirer Moydan Owner Flat',
                'purpose' => 'rent',
                'property_type' => 'Apartment',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 28000,
                'area_size' => 1320,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'garages' => 0,
                'location' => 'Mirer Moydan, Sylhet',
                'district' => 'Sylhet',
                'division' => 'Sylhet',
                'postal_code' => '3100',
                'address' => 'Porshi Building, Mirer Moydan, Sylhet',
                'description' => 'Comfortable apartment suitable for small family near central Sylhet access roads.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(11),
                'updated_at' => now()->subDays(11),
            ],
            [
                'title' => 'Chattogram Agrabad Office Floor',
                'purpose' => 'rent',
                'property_type' => 'Office',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 95000,
                'area_size' => 2100,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'garages' => 1,
                'location' => 'Agrabad, Chattogram',
                'district' => 'Chattogram',
                'division' => 'Chattogram',
                'postal_code' => '4100',
                'address' => 'Commercial Area, Agrabad, Chattogram',
                'description' => 'Office floor with open workspace and commercial access.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'title' => 'Coxs Bazar Beachside Cottage',
                'purpose' => 'sale',
                'property_type' => 'House',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 18500000,
                'area_size' => 1600,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'garages' => 1,
                'location' => 'Kolatoli, Coxs Bazar',
                'district' => 'Coxs Bazar',
                'division' => 'Chattogram',
                'postal_code' => '4700',
                'address' => 'Kolatoli Road, Coxs Bazar',
                'description' => 'Holiday-style cottage property near tourist zone.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subHours(18),
                'updated_at' => now()->subHours(18),
            ],
            [
                'title' => 'Rajshahi Padma View Duplex',
                'purpose' => 'sale',
                'property_type' => 'House',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 19800000,
                'area_size' => 2200,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'garages' => 1,
                'location' => 'Shaheb Bazar, Rajshahi',
                'district' => 'Rajshahi',
                'division' => 'Rajshahi',
                'postal_code' => '6000',
                'address' => 'Near Padma Garden, Rajshahi',
                'description' => 'Duplex home with open terrace and strong neighborhood connectivity.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(13),
                'updated_at' => now()->subDays(13),
            ],
            [
                'title' => 'Khulna Sonadanga Rental Flat',
                'purpose' => 'rent',
                'property_type' => 'Apartment',
                'status' => 'pending',
                'availability_status' => 'available',
                'price' => 24000,
                'area_size' => 1180,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'garages' => 0,
                'location' => 'Sonadanga, Khulna',
                'district' => 'Khulna',
                'division' => 'Khulna',
                'postal_code' => '9100',
                'address' => 'Main Road, Sonadanga, Khulna',
                'description' => 'Affordable rental flat in a busy residential block.',
                'contact_phone' => $user->phone ?: '01774865115',
                'review_note' => null,
                'reviewed_at' => null,
                'reviewed_by_admin_id' => null,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
        ];

        foreach ($properties as $property) {
            Property::query()->updateOrCreate(
                [
                    'user_id' => $user->id,
                    'title' => $property['title'],
                ],
                array_merge($property, [
                    'user_id' => $user->id,
                    'gallery_paths' => [],
                ])
            );
        }
    }
}
